### ISSUE TITLE
Which certs should be used

### ISSUE THREAD

**Issue by kanaabe** [artsy/artsy-eigen-web-association#6]
Posting this as an issue so I can look back if needed. I'm a little confused about the certs available in 1Password vs the ones that this repo is looking for. 

There are a few ssl cert notes available in 1Pass so I downloaded the most recently renewed ones (2016-01). However when I `make`, an error says that I don't have the right cert files. The Makefile [wants](https://github.com/artsy/artsy-eigen-web-association/blob/master/Makefile#L2) `/artsy.net.key`, `/artsy.net.crt` `artsy.net.intermediate.crt` which don't exist on that note. The 2015 one has all except `artsy.net.intermediate.crt`. I can't tell if the naming of files on 1Pass is incorrect, or the Makefile should be updated. Please let me know and thanks!

**Comment by alloy** [comment]
Actually, seeing as we’ve dropped support for iOS 8 for a while now, maybe we should just simplify this setup and only support iOS >= 9 as per #1, which means we can drop signing this file altogether.

Let me know if you need help or if you want to pair.

**Comment by kanaabe** [comment]
That's one way to do it! I read through the Support Universal Links doc and I think it'd be helpful to get some time with you to talk about details so I can do this right the first time. I'll try to find some time in the cal. Thanks.
